from tkinter import *
import pyautogui as pg
import pywhatkit as wp
import time
window = Tk()
window.title("WhatsApp Auto Wisher")
window.geometry("450x450")
window.configure(bg="#1abc9c")
number = StringVar()
message = StringVar()
def send_message(num,text):
    num = str(num)
    text = str(text)
    wp.sendwhatmsg(num, text, 14, 40,10)
    pg.press("tab")
    pg.press("tab")
    pg.press("tab")
    pg.press("tab")
    pg.press("tab")
    pg.press("tab")
    pg.press("tab")
    pg.press("tab")
    pg.press("tab")
    pg.press("enter")
def details():
    number = wp_number.get()
    message = wp_message.get()
    send_message(number, message)
Label(window, text="Whatsapp Auto wisher", font=("Hervetica","17","bold"),bg="#1abc9c").grid(row=1,column=3,padx=10,pady=6)
num1= Label(window, text="Enter Number(with country code)",bg="#1abc9c")
num1.grid(row=5,column=3,padx=10,pady=6)
wp_number = Entry(window, textvariable=number,width=35)
wp_number.grid(row=9,column=3,padx=10,pady=6)
mess1 = Label(window, text="Enter message to be sent",bg="#1abc9c")
mess1.grid(row=13,column=3,padx=10,pady=6)
wp_message = Entry(window, textvariable=message, width=70)
wp_message.grid(row=19,column=3,padx=10,pady=6)
submit = Button(window, text="Send", command=details, padx=10, pady=10, bg='#4a7abc', fg='yellow', activebackground='green', activeforeground='white').grid(row=33,column=3,padx=10,pady=6)
exitButton = Button(window, text="Exit", command=window.destroy, padx=10, pady=10, bg="red", fg='black').grid(row=35,column=3,padx=10,pady=6)
window.mainloop()
